apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-store-front
  namespace: pets
spec:
  podSelector:
    matchLabels:
      app: store-front
  policyTypes:
    - Ingress
  ingress: []

